SELECT PHONERATETYPE, DATEMONTH, SUM(TOTAL_INCOME) OVER() AS TOTAL_YEAR_INCOME,
    SUM(TOTAL_INCOME) OVER (PARTITION BY PHONERATETYPE) AS TOTAL_INCOME_FOR_PHONERATETYPE,
    SUM(TOTAL_INCOME) OVER (PARTITION BY DATEMONTH) AS TOTAL_INCOME_FOR_DATEMONTH
FROM VIEW1