SELECT DATEMONTH, PHONERATETYPE, SUM(TOTAL_INCOME) OVER() AS TOTAL_YEAR_INCOME,
    SUM(TOTAL_INCOME) OVER (PARTITION BY PHONERATETYPE) / SUM(TOTAL_INCOME) OVER() * 100,
    SUM(TOTAL_INCOME) OVER (PARTITION BY DATEMONTH) / SUM(TOTAL_INCOME) OVER() * 100
FROM VIEW1
