CREATE MATERIALIZED VIEW VIEW1
BUILD IMMEDIATE
ENABLE QUERY REWRITE
AS
SELECT P.PHONERATETYPE, T.DATEMONTH, SUM(F.PRICE) AS TOTAL_INCOME, COUNT(*) AS TOTAL_CALLS
FROM TIMEDIM T, PHONERATE P, FACTS F
WHERE T.ID_TIME = F.ID_TIME AND P.ID_PHONERATE = F.ID_PHONERATE AND T.DATEYEAR = 2003
GROUP BY P.PHONERATETYPE, T.DATEMONTH