WITH HW_INT AS (
    SELECT CodHW
    FROM HOMEWORK_DA_CONSEGARE HW
    WHERE HW.DataScadenzaPrevista >= "2021-04-01" AND HW.DataScadenzaPrevista <= "2021-04-30" AND Argomento = "ALGEBRA RELAZIONALE"
)

WITH HW_CONS_INT AS (
    SELECT MatricolaS, HW_C.CodHW, DataConsegna
    FROM HOMEWORK_CONSEGANTI HW_C, HW_INT
    WHERE HW_INT.CodHW = HW_C.CodHW
)

SELECT S.MatricolaS, Cognome
FROM HW_CONS_INT, HW_INT, STUDENTE S, HOMEWORK_CONSEGANTI HW_C
WHERE S.MatricolaS = HW_C.MatricolaS
GROUP BY S.MatricolaS, Cognome HAVING COUNT(*) = (SELECT COUNT(*) FROM HW_INT)