CREATE MATERIALIZED VIEW LOG ON Facts
WITH SEQUENCE, ROWID
(TypeOfTransportModeId, TimedimId, DayIncome, DayTicketsNumber)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON TypeOfTransportMode
WITH SEQUENCE, ROWID
(Id, Name)
INCLUDING NEW VALUES;

CREATE MATERIALIZED VIEW LOG ON Timedim
WITH SEQUENCE, ROWID
(Id, DateMonth, Year)
INCLUDING NEW VALUES;
